// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlL1x3YDBxQ7DI48C9Usj0_grbrhmvLE',
    appId: '1:366700324119:web:f5d73929868c35db7f8352',
    messagingSenderId: '366700324119',
    projectId: 'fir-authen-43aa9',
    authDomain: 'fir-authen-43aa9.firebaseapp.com',
    storageBucket: 'fir-authen-43aa9.appspot.com',
    measurementId: 'G-3V5SZ3BGJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GZjV50xCtFP8P3x2ItolK5ATJKa2XgE',
    appId: '1:366700324119:android:b404c18006c4e02d7f8352',
    messagingSenderId: '366700324119',
    projectId: 'fir-authen-43aa9',
    storageBucket: 'fir-authen-43aa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYkLBrBHqBLgjNEu5jtchtNtLJbgyOxRg',
    appId: '1:366700324119:ios:65ecbf244e0b4e887f8352',
    messagingSenderId: '366700324119',
    projectId: 'fir-authen-43aa9',
    storageBucket: 'fir-authen-43aa9.appspot.com',
    iosClientId: '366700324119-5q75ud2ka2iom4q3msf6ahurvhhc8gpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYkLBrBHqBLgjNEu5jtchtNtLJbgyOxRg',
    appId: '1:366700324119:ios:65ecbf244e0b4e887f8352',
    messagingSenderId: '366700324119',
    projectId: 'fir-authen-43aa9',
    storageBucket: 'fir-authen-43aa9.appspot.com',
    iosClientId: '366700324119-5q75ud2ka2iom4q3msf6ahurvhhc8gpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
